AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Backup automatico de todas as zonas Route53 em formato zone file BIND
  no S3, com bucket criado pelo CloudFormation, ciclo de vida avançado e
  backup a cada 12 horas.

Parameters:
  BackupBucketName:
    Type: String
    Default: route53-zones-backup-betocarrero
    Description: Bucket S3 onde os backups serão armazenados

Resources:

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BackupBucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Keep30DaysStandard
            Status: Enabled
            Prefix: ""
            ExpirationInDays: 30
          - Id: MoveToGlacier
            Status: Enabled
            Prefix: ""
            Transitions:
              - Days: 60
                StorageClass: GLACIER
            ExpirationInDays: 90

  Route53BackupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: route53-backup-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Route53BackupPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - route53:ListHostedZones
                  - route53:ListResourceRecordSets
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${BackupBucketName}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  Route53BackupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: route53-backup-lambda
      Handler: index.handler
      Runtime: python3.11
      Role: !GetAtt Route53BackupLambdaRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import datetime

          s3 = boto3.client('s3')
          route53 = boto3.client('route53')

          def handler(event, context):
              zones = route53.list_hosted_zones()['HostedZones']
              for zone in zones:
                  zone_id = zone['Id'].split('/')[-1]
                  zone_name = zone['Name']
                  record_sets = route53.list_resource_record_sets(HostedZoneId=zone_id)['ResourceRecordSets']

                  # Cria zone file BIND simples
                  zonefile = f"$ORIGIN {zone_name}\n"
                  for r in record_sets:
                      name = r['Name']
                      ttl = r.get('TTL', 300)
                      rtype = r['Type']
                      if rtype in ['CNAME', 'A', 'AAAA', 'MX', 'TXT', 'NS', 'SOA']:
                          if 'ResourceRecords' in r:
                              for rr in r['ResourceRecords']:
                                  value = rr['Value']
                                  zonefile += f"{name} {ttl} IN {rtype} {value}\n"

                  # Salva no S3
                  timestamp = datetime.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
                  key = f"{zone_name.rstrip('.')}/{timestamp}.zone"
                  s3.put_object(Bucket='${BackupBucketName}', Key=key, Body=zonefile.encode('utf-8'))

  Route53BackupSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: route53-backup-schedule
      ScheduleExpression: "cron(0 0/12 * * ? *)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt Route53BackupLambda.Arn
          Id: Route53BackupLambdaTarget

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Route53BackupLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Route53BackupSchedule.Arn
